[package]
name = "osc-music"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rosc = "0.10.1"
tokio = { version = "1.38.0", features = ["full"] }
windows = { version = "0.57.0", features = ["Media_Control", "Media", "Foundation"] }
